### ISSUE TITLE
The link not working

### ISSUE THREAD

**Issue by TrustHenry** [bosagora/agora-scan#2]
https://www.agorascan.io/validators/eth1deposits
<img width="1413" alt="스크린샷 2022-11-08 오후 4 50 02" src="https://user-images.githubusercontent.com/48541289/200504989-62a5139c-7aff-40f4-8028-6306149d5a9b.png">

https://www.agorascan.io/address/0x18c932310f6db03c9aa0d51a11d2d71596d52a8b

**Comment by MichaelKim20** [comment]
Good catch
