### ISSUE TITLE
tools/broadcast 메뉴를 활성화 합니다.

### ISSUE THREAD

**Issue by TrustHenry** [bosagora/agora-scan#22]
서명된 메세지를 브로드캐스트 하기 위한 화면을 활성화 해야 합니다.
이것은 https://beaconcha.in/tools/broadcast 와 동일한 기능 입니다.

이 화면은 BLS-to-execution 서명된 메세지를 전송 하는데 사용 될 수 있습니다.

Exit messages will be broadcasted immediately. 문구는 삭제 되어야 합니다.

**Comment by MichaelKim20** [comment]
Agora-Scan은 이기능이 포함된 최신버전으로 업그레이드 하기 어렵다고 판단됩니다.
커맨드라인으로 처리할 수 있는 방안을 찾아 봐야 겠습니다

**Comment by MichaelKim20** [comment]
페이지를 생성하는 구조가 많이 변경되어 기존코드에 추가하는것이 어려울것 같습니다.
따라서 이 기능은 제공하는것이 많은 시간이 걸리므로 해당 이슈는 닫겠습니다.
만약 새로운 방법이 생기면 다시 열어서 시도하겠습니다.
