### ISSUE TITLE
Remove 'Beacon' Phrase

### ISSUE THREAD

**Issue by TrustHenry** [bosagora/agora-scan#24]
https://testnet.agorascan.io/

<img width="1427" alt="스크린샷 2022-10-05 오후 3 57 07" src="https://user-images.githubusercontent.com/48541289/193999339-64be02d9-c8cd-43cc-99e3-c79e664f508f.png">

https://testnet.agorascan.io/validator/0x870a961a75406910ea32b14899823f38d3203ba5de42a3b5f82ecd95b8e915420742c73045813bd04056971b52dc46bc
<img width="952" alt="스크린샷 2022-10-05 오후 3 54 29" src="https://user-images.githubusercontent.com/48541289/193998934-857a984e-a618-4862-bebb-0218af70b2ba.png">

https://testnet.agorascan.io/charts

<img width="1448" alt="스크린샷 2022-10-05 오후 4 03 24" src="https://user-images.githubusercontent.com/48541289/194000328-1c2bf0fc-f4d7-4e91-9880-fa06f7af8cf2.png">

https://testnet.agorascan.io/vis
<img width="855" alt="스크린샷 2022-10-05 오후 4 04 21" src="https://user-images.githubusercontent.com/48541289/194000517-87387b4a-834d-4137-b4d4-88e0546cc371.png">

------

메뉴명 변경 Beacon Deposits -> Agora Deposits

<img width="443" alt="스크린샷 2022-10-05 오후 4 12 10" src="https://user-images.githubusercontent.com/48541289/194001712-eb5188aa-2526-4648-80fb-8b81a9d67490.png">

~~Beacon~~ **Agora** Deposits       [Home](https://testnet.agorascan.io/)
[Validators](https://testnet.agorascan.io/validators)
~~Beacon~~ **Agora** Deposits

This table displays the deposits received by the ~~Beacon Beacon~~ **Agora** Chain.

<img width="1500" alt="스크린샷 2022-10-05 오후 4 12 52" src="https://user-images.githubusercontent.com/48541289/194001836-3590a304-fc56-42b0-91b4-05a6ec028c60.png">

<img width="938" alt="스크린샷 2022-10-05 오후 3 55 23" src="https://user-images.githubusercontent.com/48541289/193999069-1565dc09-071c-49fc-94b7-aa6d88e0dabc.png">

~~Beacon~~ Agora Deposits
No agora chain deposits found for this validator. It takes [around 4 hours]~~(https://kb.beaconcha.in/ethereum-2.0-and-depositing-process)~~ for a deposit to be processed by the ~~beacon~~ agora chain.

**Comment by TrustHenry** [comment]
[around 4 hours](https://kb.beaconcha.in/ethereum-2.0-and-depositing-process)
Oh, I just wanted to take out the hyperlink.

**Comment by hewison-chris** [comment]
<img width="599" alt="Screen Shot 2022-10-17 at 9 35 18" src="https://user-images.githubusercontent.com/11815575/196068897-46c38d64-02f2-4364-8910-e920a6ec095f.png">
<img width="377" alt="Screen Shot 2022-10-17 at 9 38 28" src="https://user-images.githubusercontent.com/11815575/196068902-1fe454d2-a3f3-4351-8cf3-777b00c0a139.png">
<img width="512" alt="Screen Shot 2022-10-17 at 9 37 01" src="https://user-images.githubusercontent.com/11815575/196068903-3f57e5ed-b597-48ed-84c4-90b2cb7ec756.png">
<img width="966" alt="Screen Shot 2022-10-17 at 10 04 44" src="https://user-images.githubusercontent.com/11815575/196068964-dfff7fc8-4ced-491c-92c0-1bcb1d6b29e8.png">

Fixes in https://github.com/bosagora/agora-scan/pull/33 and https://github.com/bosagora/agora-scan/pull/34
