### ISSUE TITLE
Disable unnecessary menus 

### ISSUE THREAD

**Issue by TrustHenry** [bosagora/agora-scan#26]
https://testnet.agorascan.io/rewards
<img width="437" alt="스크린샷 2022-10-05 오후 4 09 31" src="https://user-images.githubusercontent.com/48541289/194001316-c4c34d8f-61e1-4d21-9df5-8f0f50fe6d16.png">

Income History <- disable

**Comment by hewison-chris** [comment]
https://github.com/bosagora/agora-scan/pull/33

**Comment by hewison-chris** [comment]
Now removed:

![Image](https://user-images.githubusercontent.com/11815575/196066814-d53ca245-b932-4b90-987b-0027521412d7.png)
