### ISSUE TITLE
The date is displayed in Korean.

### ISSUE THREAD

**Issue by TrustHenry** [bosagora/agora-scan#4]
Estimated between: The date is displayed in Korean.

<img width="720" alt="스크린샷 2022-11-10 오전 9 38 32" src="https://user-images.githubusercontent.com/48541289/200972046-3bae204e-f918-4c47-bcd9-14a5a5f487f2.png">

**Comment by MichaelKim20** [comment]
브라우즈의 언어설정이 원인입니다

**Comment by TrustHenry** [comment]
답변 감사합니다.
